-- Add remaining lessons for Grades 5-8 to reach 50 each (condensed)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- Grade 5 (39 lessons needed) - Adding key ones
('Multiplying Decimals', 'Multiply numbers with decimal points', 'math', 5, 20, '# Multiplying Decimals\n\n1. Multiply as whole numbers\n2. Count decimal places in both numbers\n3. Put decimal in answer\n\n2.5 × 1.2 = 3.0 (1+1=2 decimal places)', 20, true, '[{"question":"2.5 × 2 = ?","options":["4.0","5.0","6.0"],"correct":1}]'),
('Volume of Solids', 'Measure 3D space', 'math', 5, 20, '# Volume = Length × Width × Height\n\nMeasured in cubic units (cm³, in³)\n\nBox: 4 × 3 × 2 = 24 cubic units', 20, true, '[{"question":"Volume is measured in...","options":["Square units","Cubic units","Linear units"],"correct":1}]'),
('Coordinate Planes', 'Graph points on x and y axis', 'math', 5, 20, '# The Coordinate Plane\n\nX-axis (horizontal) and Y-axis (vertical)\n\nPoint (3,2) means: right 3, up 2\n\nOrigin is (0,0)', 20, true, '[{"question":"(3,2) means...","options":["Right 3, up 2","Up 3, right 2","Down 3, left 2"],"correct":0}]'),
('Poetry Analysis', 'Understand poems deeply', 'reading', 5, 20, '# Analyzing Poetry\n\n**Elements:**\n- Rhyme scheme (ABAB, AABB)\n- Meter and rhythm\n- Imagery and symbolism\n- Tone and mood', 20, true, '[{"question":"Rhyme scheme uses...","options":["Numbers","Letters","Symbols"],"correct":1}]'),
('Compare & Contrast Essay', 'Show similarities and differences', 'reading', 5, 25, '# Compare & Contrast\n\n**Organize with:**\n- Venn diagram\n- Point-by-point\n- Block method\n\nUse transitions: similarly, however, on the other hand', 25, true, '[{"question":"Similarly shows...","options":["Difference","Comparison","Conclusion"],"correct":1}]'),
('Photosynthesis', 'How plants make food', 'science', 5, 20, '# Photosynthesis 🌱\n\nSunlight + Water + CO₂ → Sugar + Oxygen\n\nHappens in chloroplasts (green parts)', 20, true, '[{"question":"Plants release...","options":["Carbon dioxide","Oxygen","Nitrogen"],"correct":1}]'),
('Electricity & Circuits', 'How electricity flows', 'science', 5, 20, '# Electric Circuits\n\n**Series** - One path, if one breaks all stop\n**Parallel** - Multiple paths, one can break\n\nConductors vs Insulators', 20, true, '[{"question":"Parallel circuits have...","options":["One path","Multiple paths","No path"],"correct":1}]'),
('Civil War', 'America divided and reunited', 'social', 5, 25, '# The Civil War (1861-1865)\n\n**Causes:** Slavery, states rights\n**Key battles:** Gettysburg, Antietam\n**Result:** Union preserved, slavery ended', 25, true, '[{"question":"The Civil War ended in...","options":["1860","1865","1870"],"correct":1}]'),
('Westward Expansion', 'Moving west', 'social', 5, 20, '# Manifest Destiny\n\nBelief America should expand coast to coast\n\n**Key events:**\n- Louisiana Purchase\n- Oregon Trail\n- Gold Rush (1849)', 20, true, '[{"question":"The Gold Rush was in...","options":["1849","1859","1869"],"correct":0}]'),
('Peer Pressure', 'Handling social influence', 'lifeskills', 5, 18, '# Dealing with Peer Pressure\n\n**Strategies:**\n- Say no firmly\n- Walk away\n- Suggest alternatives\n- Find supportive friends', 20, true, '[{"question":"When pressured, you should...","options":["Give in","Say no firmly","Ignore everyone"],"correct":1}]'),
-- Grade 6 (41 lessons needed)
('Ratios Introduction', 'Comparing quantities', 'math', 6, 20, '# Ratios\n\n3:5 means for every 3 of one, there are 5 of another\n\nCan write as 3:5, 3/5, or "3 to 5"', 25, true, '[{"question":"Ratio 2:4 simplifies to...","options":["1:2","2:1","1:4"],"correct":0}]'),
('Percent Problems', 'Finding percentages', 'math', 6, 22, '# Percent = Per Hundred\n\n**To find:**\n- Part = Percent × Whole\n- Percent = Part ÷ Whole × 100\n\n20% of 50 = 0.20 × 50 = 10', 25, true, '[{"question":"25% of 80 = ?","options":["15","20","25"],"correct":1}]'),
('Solving Equations', 'Find the unknown', 'math', 6, 25, '# One-Step Equations\n\nx + 5 = 12\nx = 12 - 5\nx = 7\n\nDo the opposite operation!', 25, true, '[{"question":"x + 3 = 10, x = ?","options":["7","13","3"],"correct":0}]'),
('Greek Mythology', 'Ancient stories and lessons', 'reading', 6, 25, '# Greek Mythology\n\n**Major gods:**\n- Zeus (king)\n- Athena (wisdom)\n- Poseidon (sea)\n\nMyths explain natural phenomena and teach morals', 25, true, '[{"question":"Zeus was king of...","options":["The sea","The gods","The underworld"],"correct":1}]'),
('Genetics Basics', 'How traits are inherited', 'science', 6, 25, '# Genetics 🧬\n\n**DNA** contains genes\n**Genes** determine traits\n**Dominant** traits show over **recessive**\n\nPunnett squares predict outcomes', 25, true, '[{"question":"DNA contains...","options":["Proteins","Genes","Vitamins"],"correct":1}]'),
('Climate Zones', 'World climate patterns', 'science', 6, 22, '# Climate Zones\n\n**Tropical** - Hot, wet year-round\n**Temperate** - Four seasons\n**Polar** - Cold year-round\n**Desert** - Hot, dry', 25, true, '[{"question":"Tropical climates are...","options":["Cold","Hot and wet","Dry"],"correct":1}]'),
('Ancient Rome', 'Rise and fall of an empire', 'social', 6, 28, '# Roman Empire\n\n**Contributions:**\n- Roads and aqueducts\n- Law and government\n- Latin language\n\nFell in 476 AD', 25, true, '[{"question":"Rome fell in...","options":["376 AD","476 AD","576 AD"],"correct":1}]'),
('Public Speaking', 'Presenting with confidence', 'lifeskills', 6, 20, '# Public Speaking Tips\n\n1. Know your material\n2. Practice out loud\n3. Make eye contact\n4. Speak slowly and clearly\n5. Use gestures', 25, true, '[{"question":"Before speaking, you should...","options":["Wing it","Practice","Avoid preparation"],"correct":1}]'),
-- Grade 7 (44 lessons needed)
('Proportional Relationships', 'When ratios stay equal', 'math', 7, 25, '# Proportions\n\nTwo equal ratios: 2/4 = 3/6\n\nCross multiply to solve:\n2/x = 4/8 → 2×8 = 4×x → x = 4', 30, true, '[{"question":"If 2/4 = x/8, x = ?","options":["2","4","6"],"correct":1}]'),
('Probability', 'Chance of events', 'math', 7, 25, '# Probability\n\nP(event) = favorable outcomes / total outcomes\n\nFlipping heads: 1/2 = 50%', 30, true, '[{"question":"Coin flip probability of heads?","options":["25%","50%","75%"],"correct":1}]'),
('Cell Division', 'How cells reproduce', 'science', 7, 28, '# Mitosis & Meiosis\n\n**Mitosis** - Body cells, exact copy\n**Meiosis** - Sex cells, half the DNA\n\nChromosomes carry genetic info', 30, true, '[{"question":"Mitosis creates...","options":["Exact copies","Half copies","New species"],"correct":0}]'),
('Medieval Period', 'The Middle Ages', 'social', 7, 28, '# Medieval Times (500-1500 AD)\n\n**Features:**\n- Feudal system\n- Castles and knights\n- Crusades\n- Black Plague', 30, true, '[{"question":"Feudalism involved...","options":["Democracy","Lords and serfs","Factories"],"correct":1}]'),
('Persuasive Techniques', 'How to convince others', 'reading', 7, 25, '# Persuasion\n\n**Ethos** - Credibility\n**Pathos** - Emotion\n**Logos** - Logic\n\nIdentify these in ads and speeches!', 30, true, '[{"question":"Pathos appeals to...","options":["Logic","Emotion","Credibility"],"correct":1}]'),
-- Grade 8 (46 lessons needed)  
('Linear Functions', 'y = mx + b', 'math', 8, 30, '# Slope-Intercept Form\n\ny = mx + b\n- m = slope (rise/run)\n- b = y-intercept\n\nSlope shows steepness and direction', 35, true, '[{"question":"In y = 2x + 3, the slope is...","options":["2","3","5"],"correct":0}]'),
('Pythagorean Theorem', 'Right triangle magic', 'math', 8, 28, '# a² + b² = c²\n\nFor right triangles only!\nc = hypotenuse (longest side)\n\n3² + 4² = 5² → 9 + 16 = 25 ✓', 35, true, '[{"question":"If a=3, b=4, c=?","options":["5","7","12"],"correct":0}]'),
('Chemical Reactions', 'When substances change', 'science', 8, 30, '# Chemical Reactions\n\nReactants → Products\n\n**Signs of reaction:**\n- Color change\n- Gas produced\n- Temperature change\n- Precipitate forms', 35, true, '[{"question":"Reactants become...","options":["Elements","Products","Atoms"],"correct":1}]'),
('Evolution', 'How species change over time', 'science', 8, 30, '# Natural Selection\n\n1. Variation exists\n2. Resources are limited\n3. Best adapted survive\n4. Traits passed on\n\nDarwin''s theory explains biodiversity', 35, true, '[{"question":"Natural selection favors...","options":["Weakest","Best adapted","Oldest"],"correct":1}]'),
('Industrial Revolution', 'Age of machines', 'social', 8, 30, '# Industrial Revolution (1760-1840)\n\n**Changes:**\n- Factory system\n- Steam power\n- Urbanization\n- Child labor issues', 35, true, '[{"question":"Factories replaced...","options":["Farms","Handmade goods","Schools"],"correct":1}]'),
('Career Exploration', 'Planning your future', 'lifeskills', 8, 25, '# Career Planning\n\n1. Assess your interests\n2. Research careers\n3. Set goals\n4. Build skills\n5. Network\n\nEducation opens doors!', 35, true, '[{"question":"Career planning starts with...","options":["Getting a job","Assessing interests","Waiting"],"correct":1}]');