-- GRADE 4 (37 more lessons to reach 50)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- G4 Reading (10)
('Figurative Language', 'Similes, metaphors, and more!', 'reading', 4, 15, '# Figurative Language 🎨\n\n**Simile** - Compares using "like" or "as"\n*She runs like the wind*\n\n**Metaphor** - Says something IS something else\n*He is a rock*\n\n**Personification** - Gives human traits to non-humans\n*The sun smiled down*', 20, true, '[{"question":"A simile uses...","options":["Like or as","No comparison","Only verbs"],"correct":0}]'),
('Point of View', 'Who is telling the story?', 'reading', 4, 15, '# Narrative Point of View\n\n**First Person** (I, we)\n*I walked to school today.*\n\n**Second Person** (you)\n*You should try this.*\n\n**Third Person** (he, she, they)\n*She opened the door.*', 20, true, '[{"question":"First person uses...","options":["He/She","I/We","You"],"correct":1}]'),
('Making Inferences', 'Read between the lines!', 'reading', 4, 18, '# Inferencing\n\nAn **inference** is an educated guess based on clues + what you know.\n\n**Clues in text** + **Your knowledge** = **Inference**\n\n*Example:* "Maria grabbed her umbrella and looked at the gray clouds."\n*Inference:* It might rain soon.', 20, true, '[{"question":"An inference is...","options":["A random guess","An educated guess using clues","A fact"],"correct":1}]'),
('Author''s Purpose', 'Why did they write it?', 'reading', 4, 15, '# Author''s Purpose: PIE 🥧\n\n**P**ersuade - Change your mind\n**I**nform - Teach you facts\n**E**ntertain - Make you enjoy\n\n*Ask: Why did the author write this?*', 20, true, '[{"question":"PIE stands for...","options":["Persuade, Inform, Entertain","People, Ideas, Events","Pictures, Images, Examples"],"correct":0}]'),
('Text Structure', 'How text is organized', 'reading', 4, 18, '# Text Structures\n\n**Chronological** - Time order\n**Compare/Contrast** - Similarities and differences\n**Cause/Effect** - What happened and why\n**Problem/Solution** - Issue and how it was fixed\n**Description** - Details about a topic', 20, true, '[{"question":"Cause and effect shows...","options":["Time order","What happened and why","Similarities"],"correct":1}]'),
('Theme vs Topic', 'What''s the difference?', 'reading', 4, 15, '# Theme vs Topic\n\n**Topic** = What the story is about (one word)\n*Example: Friendship*\n\n**Theme** = The message or lesson (a sentence)\n*Example: True friends stick together through hard times.*', 20, true, '[{"question":"Theme is...","options":["One word","A message or lesson","The title"],"correct":1}]'),
('Summary Writing', 'Tell the main points briefly', 'reading', 4, 18, '# How to Summarize\n\n**Include:**\n- Main characters\n- Setting\n- Main problem\n- How it was solved\n\n**Don''t include:**\n- Small details\n- Your opinions\n- Every event', 20, true, '[{"question":"A summary should be...","options":["Longer than original","Brief with main points","Full of your opinions"],"correct":1}]'),
('Root Words', 'The building blocks of words', 'reading', 4, 15, '# Root Words 🌳\n\nRoots are the base of words:\n\n**bio** = life (biology, biography)\n**graph** = write (autograph, paragraph)\n**port** = carry (transport, export)\n**ject** = throw (project, inject)', 20, true, '[{"question":"Bio means...","options":["Water","Life","Earth"],"correct":1}]'),
('Greek & Latin Roots', 'Ancient word parts', 'reading', 4, 18, '# Greek & Latin Roots\n\n**Greek:**\n- *tele* = far (telephone, telescope)\n- *auto* = self (automatic, automobile)\n\n**Latin:**\n- *aud* = hear (audio, audience)\n- *vis* = see (visible, vision)', 20, true, '[{"question":"Tele means...","options":["Near","Far","Same"],"correct":1}]'),
('Text Evidence', 'Prove it with the text!', 'reading', 4, 15, '# Using Text Evidence\n\n**ACE Your Answers:**\n- **A**nswer the question\n- **C**ite evidence from text\n- **E**xplain how it supports your answer\n\n*Use quotation marks around exact words from the text!*', 20, true, '[{"question":"ACE stands for...","options":["Answer, Cite, Explain","Ask, Create, Edit","Always, Compare, Evaluate"],"correct":0}]'),
-- G4 Math (10)
('Multi-Digit Multiplication', 'Multiply larger numbers!', 'math', 4, 20, '# Multiplying Multi-Digit Numbers\n\n**23 × 14 = ?**\n\nStep 1: 23 × 4 = 92\nStep 2: 23 × 10 = 230\nStep 3: 92 + 230 = **322**\n\n*Stack, multiply, add!*', 20, true, '[{"question":"23 × 14 = ?","options":["222","322","422"],"correct":1}]'),
('Long Division', 'Divide larger numbers!', 'math', 4, 22, '# Long Division 📝\n\n**156 ÷ 12 = ?**\n\nUse: **D**ivide, **M**ultiply, **S**ubtract, **B**ring down\n\n12 goes into 15 = 1 time\n12 × 1 = 12, 15 - 12 = 3\nBring down 6 → 36\n12 goes into 36 = 3 times\n\nAnswer: **13**', 20, true, '[{"question":"156 ÷ 12 = ?","options":["11","12","13"],"correct":2}]'),
('Equivalent Fractions', 'Same value, different look!', 'math', 4, 18, '# Equivalent Fractions\n\n1/2 = 2/4 = 3/6 = 4/8\n\n**To find equivalent fractions:**\nMultiply top AND bottom by same number!\n\n1/3 × 2/2 = 2/6 ✓', 20, true, '[{"question":"1/2 = ?/4","options":["1","2","3"],"correct":1}]'),
('Adding Fractions', 'Same denominators first!', 'math', 4, 18, '# Adding Fractions\n\n**Same denominator:** Add numerators\n1/4 + 2/4 = 3/4\n\n**Different denominators:** Find common denominator first!\n1/2 + 1/4 = 2/4 + 1/4 = 3/4', 20, true, '[{"question":"1/4 + 2/4 = ?","options":["3/4","3/8","2/4"],"correct":0}]'),
('Decimals & Place Value', 'Tenths and hundredths', 'math', 4, 18, '# Decimal Place Value\n\n**3.45**\n- 3 = ones\n- 4 = tenths (0.4)\n- 5 = hundredths (0.05)\n\nRead as: "Three and forty-five hundredths"', 20, true, '[{"question":"In 2.37, the 7 is in the...","options":["Tens place","Tenths place","Hundredths place"],"correct":2}]'),
('Perimeter & Area', 'Around and inside!', 'math', 4, 18, '# Perimeter & Area\n\n**Perimeter** = Distance around\nP = 2l + 2w\n\n**Area** = Space inside\nA = l × w\n\n*Rectangle 4×3:*\nPerimeter = 14 units\nArea = 12 square units', 20, true, '[{"question":"Area is measured in...","options":["Units","Square units","Cubic units"],"correct":1}]'),
('Factors & Multiples', 'Number families!', 'math', 4, 15, '# Factors & Multiples\n\n**Factors** of 12: 1, 2, 3, 4, 6, 12\n(Numbers that divide evenly into 12)\n\n**Multiples** of 3: 3, 6, 9, 12, 15...\n(3 times something)', 20, true, '[{"question":"Factors of 8 include...","options":["3","4","5"],"correct":1}]'),
('Prime & Composite', 'Special number types!', 'math', 4, 15, '# Prime & Composite Numbers\n\n**Prime** = Only factors are 1 and itself\n2, 3, 5, 7, 11, 13...\n\n**Composite** = Has more factors\n4, 6, 8, 9, 10...\n\n*1 is neither prime nor composite!*', 20, true, '[{"question":"7 is...","options":["Prime","Composite","Neither"],"correct":0}]'),
('Angles', 'Acute, right, obtuse, straight!', 'math', 4, 15, '# Types of Angles 📐\n\n**Acute** = Less than 90°\n**Right** = Exactly 90°\n**Obtuse** = More than 90°\n**Straight** = Exactly 180°', 20, true, '[{"question":"An angle of 45° is...","options":["Acute","Right","Obtuse"],"correct":0}]'),
('Line Symmetry', 'Mirror images!', 'math', 4, 15, '# Symmetry ↔️\n\nA shape has **line symmetry** if you can fold it and both sides match!\n\n✓ Square - 4 lines of symmetry\n✓ Circle - infinite lines\n✗ Scalene triangle - 0 lines', 20, true, '[{"question":"A square has how many lines of symmetry?","options":["2","4","6"],"correct":1}]'),
-- G4 Science (8)
('The Water Cycle', 'Water moves around!', 'science', 4, 18, '# The Water Cycle 💧\n\n**Evaporation** - Water heats up and rises as vapor\n**Condensation** - Vapor cools and forms clouds\n**Precipitation** - Water falls as rain/snow\n**Collection** - Water gathers in lakes/oceans\n\n*Then it starts again!*', 20, true, '[{"question":"Clouds form during...","options":["Evaporation","Condensation","Precipitation"],"correct":1}]'),
('Electricity Basics', 'How does it flow?', 'science', 4, 18, '# Electricity ⚡\n\n**Circuit** = Path for electricity to flow\n\n**Needs:**\n- Power source (battery)\n- Conductor (wire)\n- Load (light bulb)\n\n*Circuit must be complete for electricity to flow!*', 20, true, '[{"question":"Electricity needs a complete...","options":["Circle","Circuit","Container"],"correct":1}]'),
('Magnets', 'Attract and repel!', 'science', 4, 15, '# Magnets 🧲\n\n**Attract** = Pull together (N-S)\n**Repel** = Push apart (N-N or S-S)\n\n*Opposites attract!*\n\nMagnets attract: Iron, steel, nickel\nMagnets don''t attract: Wood, plastic, glass', 20, true, '[{"question":"Opposite poles...","options":["Repel","Attract","Nothing"],"correct":1}]'),
('Rocks & Minerals', 'Earth''s building blocks!', 'science', 4, 18, '# Types of Rocks 🪨\n\n**Igneous** - From cooled lava/magma\n**Sedimentary** - Layers pressed together\n**Metamorphic** - Changed by heat and pressure\n\n*The rock cycle transforms rocks from one type to another!*', 20, true, '[{"question":"Rocks from cooled lava are...","options":["Igneous","Sedimentary","Metamorphic"],"correct":0}]'),
('Weather vs Climate', 'Short-term vs long-term!', 'science', 4, 15, '# Weather vs Climate\n\n**Weather** = Daily conditions\n*"It''s sunny today!"*\n\n**Climate** = Average weather over many years\n*"Florida has a warm climate."*\n\n*Weather changes daily; climate changes slowly.*', 20, true, '[{"question":"Climate is...","options":["Today''s weather","Average weather over years","Tomorrow''s forecast"],"correct":1}]'),
('Energy Forms', 'Energy is everywhere!', 'science', 4, 18, '# Forms of Energy\n\n**Kinetic** - Energy of motion\n**Potential** - Stored energy\n**Heat** - Thermal energy\n**Light** - Radiant energy\n**Sound** - Vibration energy\n**Electrical** - Moving electrons', 20, true, '[{"question":"Energy of motion is...","options":["Potential","Kinetic","Thermal"],"correct":1}]'),
('Adaptations', 'How organisms survive!', 'science', 4, 18, '# Animal Adaptations 🦎\n\n**Structural** - Body parts\n*Giraffe''s long neck*\n\n**Behavioral** - Actions\n*Bears hibernating*\n\n**Physiological** - Body processes\n*Snakes use venom*', 20, true, '[{"question":"Hibernation is what type of adaptation?","options":["Structural","Behavioral","Physiological"],"correct":1}]'),
('Solar System Planets', 'Our cosmic neighborhood!', 'science', 4, 20, '# The 8 Planets 🪐\n\n**Inner (Rocky):**\nMercury, Venus, Earth, Mars\n\n**Outer (Gas Giants):**\nJupiter, Saturn, Uranus, Neptune\n\n*My Very Educated Mother Just Served Us Nachos!*', 20, true, '[{"question":"Which planet is closest to the Sun?","options":["Venus","Mercury","Earth"],"correct":1}]'),
-- G4 Social (5)
('Branches of Government', 'Three branches, one government!', 'social', 4, 18, '# Three Branches 🏛️\n\n**Legislative** - Makes laws (Congress)\n**Executive** - Enforces laws (President)\n**Judicial** - Interprets laws (Supreme Court)\n\n*Checks and balances keep them equal!*', 20, true, '[{"question":"Who makes laws?","options":["President","Congress","Supreme Court"],"correct":1}]'),
('Native American Regions', 'First peoples of America', 'social', 4, 18, '# Native American Cultures\n\n**Eastern Woodlands** - Longhouses, farming\n**Plains** - Tipis, buffalo hunting\n**Southwest** - Pueblos, irrigation\n**Pacific Northwest** - Totem poles, fishing\n\n*Each region shaped their way of life!*', 20, true, '[{"question":"Plains tribes hunted...","options":["Fish","Buffalo","Seals"],"correct":1}]'),
('Explorers', 'Adventurers who discovered new lands', 'social', 4, 18, '# Famous Explorers 🧭\n\n**Columbus** (1492) - Reached Americas\n**Magellan** - First to sail around world\n**Lewis & Clark** - Explored western US\n**Sacagawea** - Guided Lewis & Clark\n\n*Exploration changed the world!*', 20, true, '[{"question":"Columbus reached America in...","options":["1392","1492","1592"],"correct":1}]'),
('Resources: Natural, Human, Capital', 'What we use to make things!', 'social', 4, 15, '# Types of Resources\n\n**Natural** - From nature (water, wood, oil)\n**Human** - People and their skills\n**Capital** - Tools and machines\n\n*All three needed to produce goods!*', 20, true, '[{"question":"Trees are what type of resource?","options":["Natural","Human","Capital"],"correct":0}]'),
('Regions of the United States', 'Different areas, different features!', 'social', 4, 18, '# US Regions\n\n**Northeast** - Cities, history\n**Southeast** - Warm, humid\n**Midwest** - Farmland, plains\n**Southwest** - Deserts, canyons\n**West** - Mountains, coast\n\n*Each region has unique geography and culture!*', 20, true, '[{"question":"The Midwest is known for...","options":["Deserts","Farmland","Beaches"],"correct":1}]'),
-- G4 Life Skills (4)
('Growth Mindset', 'Your brain can grow!', 'lifeskills', 4, 15, '# Growth Mindset 🧠\n\n**Fixed Mindset:** "I can''t do this."\n**Growth Mindset:** "I can''t do this YET."\n\nMistakes help your brain grow!\nChallenge yourself to improve!', 20, true, '[{"question":"Growth mindset says...","options":["I''ll never learn","I can improve with practice","Give up easily"],"correct":1}]'),
('Note-Taking Skills', 'Capture important information!', 'lifeskills', 4, 15, '# Taking Good Notes 📝\n\n**Tips:**\n- Write main ideas, not everything\n- Use abbreviations\n- Organize with headings\n- Review notes same day\n- Ask questions in margins', 20, true, '[{"question":"Good notes include...","options":["Every word","Main ideas","Only drawings"],"correct":1}]'),
('Test-Taking Strategies', 'Do your best on tests!', 'lifeskills', 4, 15, '# Test Success Tips 📋\n\n1. Read directions carefully\n2. Answer easy questions first\n3. Eliminate wrong answers\n4. Check your work\n5. Manage your time\n\n*Stay calm and do your best!*', 20, true, '[{"question":"First, you should...","options":["Panic","Read directions","Skip everything"],"correct":1}]'),
('Conflict Resolution', 'Solve problems peacefully', 'lifeskills', 4, 15, '# Resolving Conflicts 🕊️\n\n**STOP** - Calm down first\n**THINK** - What happened? How do I feel?\n**TALK** - Use "I" statements\n**LISTEN** - Hear their side\n**SOLVE** - Find a fair solution', 20, true, '[{"question":"First step in conflict resolution?","options":["Yell","Stop and calm down","Run away"],"correct":1}]');