-- Grade 6 Lessons (33 more needed to reach 50)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- G6 Math (10 more)
('Solving One-Step Equations', 'Isolating the variable', 'math', 6, 22, '# One-Step Equations\n\n**Goal:** Get x alone!\n\n**Addition:** x + 5 = 12 → x = 7\n**Subtraction:** x - 3 = 8 → x = 11\n**Multiplication:** 4x = 20 → x = 5\n**Division:** x/3 = 6 → x = 18', 25, true, '[{"question":"Solve: x + 7 = 15","options":["x=7","x=8","x=22","x=15"],"correct":1}]'),
('Absolute Value', 'Distance from zero', 'math', 6, 20, '# Absolute Value\n\n|x| = distance from 0\n\n|5| = 5\n|-5| = 5\n|0| = 0\n\nAlways positive or zero!', 22, true, '[{"question":"What is |-7|?","options":["-7","7","0","14"],"correct":1}]'),
('Exponents Introduction', 'Powers of numbers', 'math', 6, 22, '# Exponents\n\n3⁴ = 3 × 3 × 3 × 3 = 81\n\n**Base** = the number being multiplied\n**Exponent** = how many times\n\n2⁵ = 32\n10² = 100\n5⁰ = 1 (anything to 0 = 1)', 25, true, '[{"question":"What is 2⁴?","options":["6","8","16","32"],"correct":2}]'),
('Ratio Applications', 'Using ratios in real life', 'math', 6, 22, '# Ratio Applications\n\n**Recipe scaling:** Double a recipe = multiply all by 2\n\n**Unit rates:** $30 for 5 items = $6 per item\n\n**Map scales:** 1 inch = 10 miles', 22, true, '[{"question":"$24 for 6 items = $ per item?","options":["$2","$4","$6","$8"],"correct":1}]'),
('Area of Triangles and Parallelograms', 'More 2D shapes', 'math', 6, 22, '# Area Formulas\n\n**Triangle:** A = ½ × base × height\n**Parallelogram:** A = base × height\n\nTriangle with b=6, h=4: A = ½×6×4 = 12 sq units', 22, true, '[{"question":"Triangle area: b=10, h=6?","options":["60","30","16","20"],"correct":1}]'),
('Distributive Property', 'Multiplying across parentheses', 'math', 6, 20, '# Distributive Property\n\na(b + c) = ab + ac\n\n3(x + 4) = 3x + 12\n5(2y - 3) = 10y - 15\n\nMultiply each term inside!', 22, true, '[{"question":"2(x + 5) = ?","options":["2x + 5","2x + 10","x + 10","2x + 7"],"correct":1}]'),
('Greatest Common Factor', 'Largest shared factor', 'math', 6, 20, '# GCF\n\nGCF of 12 and 18:\n12: 1, 2, 3, 4, 6, 12\n18: 1, 2, 3, 6, 9, 18\n\nShared: 1, 2, 3, 6\nGCF = 6', 20, true, '[{"question":"GCF of 8 and 12?","options":["2","4","8","24"],"correct":1}]'),
('Least Common Multiple', 'Smallest shared multiple', 'math', 6, 20, '# LCM\n\nLCM of 4 and 6:\n4: 4, 8, 12, 16, 20...\n6: 6, 12, 18, 24...\n\nLCM = 12 (first shared)', 20, true, '[{"question":"LCM of 3 and 5?","options":["8","15","3","5"],"correct":1}]'),
('Box Plots', 'Visualizing data spread', 'math', 6, 22, '# Box Plots\n\nShow data distribution:\n\n**Minimum** → **Q1** → **Median** → **Q3** → **Maximum**\n\nThe box shows the middle 50% of data', 22, true, '[{"question":"Box plot shows the middle...","options":["25%","50%","75%","100%"],"correct":1}]'),
('Writing Inequalities', 'Greater than, less than', 'math', 6, 20, '# Inequalities\n\n< less than\n> greater than\n≤ less than or equal\n≥ greater than or equal\n\nx > 5 means x is more than 5\nx ≤ 10 means x is 10 or less', 20, true, '[{"question":"x ≥ 3 includes...","options":["Only 3","Less than 3","3 and greater","Only greater"],"correct":2}]'),
-- G6 Reading (8 more)
('Analyzing Poetry', 'Understanding poems', 'reading', 6, 25, '# Poetry Analysis\n\n**Elements:**\n- Rhyme scheme (ABAB, AABB)\n- Meter (rhythm pattern)\n- Stanzas (verse paragraphs)\n- Imagery (sensory details)\n- Tone (author''s attitude)', 25, true, '[{"question":"Verse paragraphs are called...","options":["Lines","Stanzas","Rhymes","Meters"],"correct":1}]'),
('Drama Elements', 'Understanding plays', 'reading', 6, 22, '# Drama Terms\n\n**Act** = major section\n**Scene** = smaller division\n**Dialogue** = characters speaking\n**Stage directions** = actions in italics/brackets\n**Monologue** = long speech by one', 22, true, '[{"question":"A long speech by one character?","options":["Dialogue","Monologue","Aside","Scene"],"correct":1}]'),
('Primary vs Secondary Sources', 'Types of information', 'reading', 6, 20, '# Sources\n\n**Primary** = firsthand\n- Diaries, letters, photos, interviews\n\n**Secondary** = analyzed/interpreted\n- Textbooks, documentaries, biographies\n\nPrimary is closer to the event!', 20, true, '[{"question":"A diary is which source?","options":["Primary","Secondary","Tertiary","None"],"correct":0}]'),
('Persuasive Techniques', 'How writers convince', 'reading', 6, 22, '# Persuasive Techniques\n\n**Ethos** = credibility/trust\n**Pathos** = emotion\n**Logos** = logic/facts\n\n**Also:**\n- Bandwagon ("everyone does it")\n- Testimonial (celebrity endorsement)\n- Repetition', 22, true, '[{"question":"Appeal to emotion is...","options":["Ethos","Pathos","Logos","Bandwagon"],"correct":1}]'),
('Comparing Texts', 'Multiple sources on same topic', 'reading', 6, 25, '# Comparing Texts\n\n**Consider:**\n- Different perspectives\n- Conflicting information\n- Author bias\n- Purpose differences\n\nComparing helps find the truth!', 25, true, '[{"question":"Why compare texts?","options":["It is fun","Find different perspectives","Read faster","Avoid homework"],"correct":1}]'),
('Citing Evidence', 'Supporting your claims', 'reading', 6, 22, '# Citing Evidence\n\n**Steps:**\n1. Make your claim\n2. Introduce the quote\n3. Include the quote\n4. Explain how it supports your claim\n\nUse quotation marks and page numbers!', 22, true, '[{"question":"After a quote you should...","options":["Stop","Explain it","Make another claim","Nothing"],"correct":1}]'),
('Central Idea', 'Main message of nonfiction', 'reading', 6, 20, '# Central Idea\n\n**Central idea** = main point of nonfiction\n\n**Find it by:**\n- What is the topic?\n- What does the author say about it?\n- What details support this?\n\nNot stated directly - you infer it!', 20, true, '[{"question":"Central idea is...","options":["The topic","Main point","First sentence","Conclusion only"],"correct":1}]'),
('Connotation vs Denotation', 'Word meanings and feelings', 'reading', 6, 18, '# Connotation vs Denotation\n\n**Denotation** = dictionary definition\n**Connotation** = emotional feeling\n\n"Cheap" vs "Affordable"\nSame denotation, different connotation!', 18, true, '[{"question":"Emotional meaning is...","options":["Denotation","Connotation","Definition","Synonym"],"correct":1}]'),
-- G6 Science (8 more)
('Energy Transfer', 'How energy moves', 'science', 6, 25, '# Energy Transfer\n\n**Conduction** = direct contact (hot pan)\n**Convection** = through fluids (boiling water)\n**Radiation** = waves through space (sunlight)\n\nEnergy flows from hot to cold!', 25, true, '[{"question":"Energy through direct contact?","options":["Radiation","Convection","Conduction","Reflection"],"correct":2}]'),
('Photosynthesis', 'How plants make food', 'science', 6, 25, '# Photosynthesis\n\n**Equation:**\nSunlight + Water + CO₂ → Glucose + Oxygen\n\nHappens in **chloroplasts**\nChlorophyll makes leaves green!', 25, true, '[{"question":"Plants make their own...","options":["Water","Sunlight","Food/glucose","Carbon dioxide"],"correct":2}]'),
('Cellular Respiration', 'How cells use energy', 'science', 6, 25, '# Cellular Respiration\n\n**Equation:**\nGlucose + Oxygen → Energy + CO₂ + Water\n\nOpposite of photosynthesis!\nHappens in **mitochondria**', 25, true, '[{"question":"Respiration happens in...","options":["Chloroplasts","Mitochondria","Nucleus","Cell wall"],"correct":1}]'),
('Classification of Living Things', 'Organizing life', 'science', 6, 22, '# Classification\n\n**Taxonomy levels:**\nKingdom → Phylum → Class → Order → Family → Genus → Species\n\n**Remember:** King Philip Came Over For Good Soup', 22, true, '[{"question":"Most specific level?","options":["Kingdom","Family","Genus","Species"],"correct":3}]'),
('Earth''s Layers', 'Inside our planet', 'science', 6, 22, '# Earth''s Layers\n\n**Crust** = thin outer layer\n**Mantle** = thick, semi-solid\n**Outer Core** = liquid metal\n**Inner Core** = solid metal (hottest)', 22, true, '[{"question":"Which layer is liquid?","options":["Crust","Mantle","Outer core","Inner core"],"correct":2}]'),
('Minerals and Rocks', 'Earth materials', 'science', 6, 22, '# Rocks & Minerals\n\n**Three rock types:**\n- **Igneous** = from cooled magma\n- **Sedimentary** = from compressed layers\n- **Metamorphic** = changed by heat/pressure\n\nThe rock cycle connects them!', 22, true, '[{"question":"Cooled magma makes...","options":["Sedimentary","Metamorphic","Igneous","Minerals"],"correct":2}]'),
('Force and Motion Review', 'Physics fundamentals', 'science', 6, 25, '# Force and Motion\n\n**Force** = push or pull\n**Net force** = all forces combined\n**Balanced** = no movement change\n**Unbalanced** = causes acceleration\n\nF = m × a', 25, true, '[{"question":"Unbalanced forces cause...","options":["Nothing","Acceleration","Balance","Rest"],"correct":1}]'),
('Density', 'Mass per volume', 'science', 6, 22, '# Density\n\n**Density = Mass ÷ Volume**\n\nd = m/v\n\nObjects with higher density sink!\nWater density = 1 g/cm³\n\nIf d > 1, it sinks in water', 22, true, '[{"question":"Density formula?","options":["m × v","m + v","m ÷ v","m - v"],"correct":2}]'),
-- G6 Social (5 more)
('Early Civilizations Review', 'Foundations of society', 'social', 6, 25, '# Early Civilizations\n\n**River Valley Civilizations:**\n- Mesopotamia (Tigris/Euphrates)\n- Egypt (Nile)\n- India (Indus)\n- China (Yellow River)\n\nWater = agriculture = cities!', 25, true, '[{"question":"Egypt developed near...","options":["Tigris","Nile","Indus","Yellow"],"correct":1}]'),
('Medieval Europe', 'The Middle Ages', 'social', 6, 25, '# Medieval Europe\n\n**Feudal System:**\nKing → Lords → Knights → Peasants\n\n**Key features:**\n- Manors and castles\n- Catholic Church power\n- Crusades (1095-1291)\n- Black Death (1347)', 25, true, '[{"question":"Who was at top of feudal system?","options":["Lords","Knights","King","Peasants"],"correct":2}]'),
('Renaissance', 'Rebirth of learning', 'social', 6, 25, '# The Renaissance\n\n**When:** 1400s-1600s\n**Where:** Started in Italy\n\n**Key ideas:**\n- Humanism\n- Art and science flourished\n- Leonardo, Michelangelo\n- Printing press (1450s)', 25, true, '[{"question":"Renaissance started in...","options":["France","England","Italy","Spain"],"correct":2}]'),
('Age of Exploration', 'Discovering new worlds', 'social', 6, 25, '# Age of Exploration\n\n**Why:** Spices, wealth, spreading Christianity\n\n**Key explorers:**\n- Columbus (1492)\n- Magellan (circumnavigate)\n- Cortés, Pizarro (conquistadors)\n\n**Impact:** Columbian Exchange', 25, true, '[{"question":"Columbus sailed in...","options":["1392","1492","1592","1692"],"correct":1}]'),
('Branches of Government', 'How democracy works', 'social', 6, 25, '# Three Branches\n\n**Legislative** = Congress (makes laws)\n**Executive** = President (enforces laws)\n**Judicial** = Courts (interprets laws)\n\n**Checks and balances** = each limits others', 25, true, '[{"question":"Who makes laws?","options":["President","Courts","Congress","Police"],"correct":2}]'),
-- G6 Lifeskills (2 more)
('Stress Management', 'Handling pressure', 'lifeskills', 6, 22, '# Managing Stress\n\n**Healthy coping:**\n- Exercise and sleep\n- Talk to someone\n- Break tasks into steps\n- Deep breathing\n- Take breaks\n\n**Avoid:** avoiding problems, unhealthy habits', 22, true, '[{"question":"Healthy stress response?","options":["Ignore it","Exercise","Stay up late","Skip meals"],"correct":1}]'),
('Peer Pressure', 'Making your own choices', 'lifeskills', 6, 20, '# Handling Peer Pressure\n\n**Recognize it:**\n- "Everyone is doing it"\n- "You''re not cool if you don''t"\n\n**Respond:**\n- Say no firmly\n- Suggest alternatives\n- Walk away\n- Find supportive friends', 20, true, '[{"question":"Best response to peer pressure?","options":["Give in","Say no firmly","Avoid friends","Do nothing"],"correct":1}]');