-- Grade 5 Lessons (29 more needed to reach 50)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- G5 Math (10 more)
('Percentages Intro', 'Understanding percentages', 'math', 5, 20, '# Percentages\n\nPercent means "per hundred"!\n\n50% = 50/100 = 0.5 = 1/2\n25% = 25/100 = 0.25 = 1/4\n\n**To find percent of a number:**\n50% of 80 = 0.5 × 80 = 40', 20, true, '[{"question":"What is 50% of 100?","options":["25","50","75","100"],"correct":1}]'),
('Coordinate Graphing', 'Plotting points on a grid', 'math', 5, 20, '# Coordinate Plane\n\n**X-axis** = horizontal\n**Y-axis** = vertical\n\nPoints written as (x, y)\n(3, 4) means go right 3, up 4\n\nThe center is called the **origin** (0, 0)', 20, true, '[{"question":"In (5, 2), what is the x-coordinate?","options":["2","5","7","0"],"correct":1}]'),
('Prime and Composite', 'Types of numbers', 'math', 5, 18, '# Prime vs Composite\n\n**Prime** = only divisible by 1 and itself\nExamples: 2, 3, 5, 7, 11, 13\n\n**Composite** = has more factors\nExamples: 4, 6, 8, 9, 10, 12\n\n**1 is neither prime nor composite!**', 18, true, '[{"question":"Is 7 prime or composite?","options":["Prime","Composite","Neither","Both"],"correct":0}]'),
('Mean, Median, Mode', 'Measures of central tendency', 'math', 5, 22, '# Mean, Median, Mode\n\nData: 2, 4, 4, 6, 8\n\n**Mean** = average = (2+4+4+6+8)/5 = 4.8\n**Median** = middle value = 4\n**Mode** = most frequent = 4', 22, true, '[{"question":"What is the mode of 1, 2, 2, 3?","options":["1","2","3","2.5"],"correct":1}]'),
('Multi-Digit Multiplication', 'Multiplying larger numbers', 'math', 5, 20, '# Multi-Digit Multiplication\n\n**23 × 45**\n1. 23 × 5 = 115\n2. 23 × 40 = 920\n3. Add: 115 + 920 = 1,035\n\nAlways line up place values!', 20, true, '[{"question":"12 × 25 = ?","options":["250","275","300","325"],"correct":2}]'),
('Long Division', 'Dividing with remainders', 'math', 5, 22, '# Long Division\n\n**156 ÷ 12 = 13**\n\nSteps: Divide, Multiply, Subtract, Bring down\n\nCheck: 13 × 12 = 156 ✓', 22, true, '[{"question":"144 ÷ 12 = ?","options":["10","11","12","14"],"correct":2}]'),
('Volume of Rectangular Prisms', 'Measuring 3D space', 'math', 5, 20, '# Volume\n\n**Volume = length × width × height**\n\nV = l × w × h\n\nA box 4×3×2 = 24 cubic units\n\nUnits: cubic cm, cubic m, cubic in', 20, true, '[{"question":"Volume of 5×2×3 box?","options":["10","25","30","35"],"correct":2}]'),
('Adding Fractions', 'Same and different denominators', 'math', 5, 20, '# Adding Fractions\n\n**Same denominator:**\n1/4 + 2/4 = 3/4\n\n**Different denominators:**\n1/2 + 1/4 = 2/4 + 1/4 = 3/4\n\nFind common denominator first!', 20, true, '[{"question":"1/3 + 1/3 = ?","options":["1/6","2/6","2/3","1"],"correct":2}]'),
('Converting Units', 'Metric and customary', 'math', 5, 18, '# Unit Conversions\n\n**Length:**\n12 inches = 1 foot\n3 feet = 1 yard\n\n**Metric:**\n100 cm = 1 m\n1000 m = 1 km', 18, true, '[{"question":"How many inches in 2 feet?","options":["12","24","36","48"],"correct":1}]'),
('Word Problems Strategy', 'Solving multi-step problems', 'math', 5, 22, '# Word Problem Steps\n\n1. **Read** carefully\n2. **Identify** what you need to find\n3. **Plan** your approach\n4. **Solve** step by step\n5. **Check** your answer', 22, true, '[{"question":"First step in solving word problems?","options":["Solve","Plan","Read","Check"],"correct":2}]'),
-- G5 Reading (8 more)
('Figurative Language', 'Beyond literal meaning', 'reading', 5, 20, '# Figurative Language\n\n**Simile** = uses "like" or "as"\n"Fast as lightning"\n\n**Metaphor** = direct comparison\n"Life is a journey"\n\n**Personification** = giving human traits\n"The wind whispered"', 20, true, '[{"question":"Uses like or as?","options":["Metaphor","Simile","Personification","Hyperbole"],"correct":1}]'),
('Point of View', 'Who tells the story?', 'reading', 5, 18, '# Point of View\n\n**First Person** = I, me, my\n**Second Person** = you, your\n**Third Person Limited** = he/she, one character\n**Third Person Omniscient** = knows all characters', 18, true, '[{"question":"Which uses I and me?","options":["First person","Second person","Third person","None"],"correct":0}]'),
('Making Inferences', 'Reading between lines', 'reading', 5, 20, '# Inferences\n\nInference = conclusion from clues + what you know\n\n**Text says:** "She grabbed her umbrella."\n**I know:** Umbrellas are for rain\n**Inference:** It might rain', 20, true, '[{"question":"An inference is...","options":["A guess","A fact stated","A conclusion from clues","The title"],"correct":2}]'),
('Text Structure', 'How writing is organized', 'reading', 5, 20, '# Text Structures\n\n**Chronological** = time order\n**Compare/Contrast** = similarities/differences\n**Cause/Effect** = why things happen\n**Problem/Solution** = issue and fix\n**Description** = details about a topic', 20, true, '[{"question":"Time order is called?","options":["Compare","Chronological","Cause/effect","Description"],"correct":1}]'),
('Context Clues', 'Finding word meaning', 'reading', 5, 18, '# Context Clues\n\nUse surrounding words to find meaning!\n\n**Types:**\n- Definition (word is explained)\n- Synonym (similar word nearby)\n- Antonym (opposite nearby)\n- Example (examples given)', 18, true, '[{"question":"Context clues help you...","options":["Spell words","Find word meaning","Count words","Write faster"],"correct":1}]'),
('Summarizing', 'Main ideas briefly', 'reading', 5, 18, '# Summarizing\n\nA summary includes:\n- Main idea\n- Key details only\n- Your own words\n- Much shorter than original\n\nDon''t include opinions or minor details!', 18, true, '[{"question":"A summary should be...","options":["Longer than original","Your opinion","Brief main ideas","Word for word"],"correct":2}]'),
('Author''s Purpose', 'Why did they write it?', 'reading', 5, 18, '# Author''s Purpose\n\n**P**ersuade = convince you\n**I**nform = teach facts\n**E**ntertain = enjoyment\n\nRemember: **PIE**\n\nLook for clues in the text!', 18, true, '[{"question":"PIE stands for...","options":["Plot, Intro, End","Persuade, Inform, Entertain","People, Ideas, Events","None"],"correct":1}]'),
('Biography vs Autobiography', 'Types of life stories', 'reading', 5, 18, '# Life Stories\n\n**Biography** = written by someone else\n**Autobiography** = written by the person\n**Memoir** = focuses on specific memories\n\nAll are nonfiction!', 18, true, '[{"question":"Written by the person themselves?","options":["Biography","Autobiography","Fiction","News"],"correct":1}]'),
-- G5 Science (6 more)
('Food Chains', 'Energy transfer in ecosystems', 'science', 5, 22, '# Food Chains\n\n**Sun → Producer → Consumer → Consumer**\n\nSun → Grass → Rabbit → Fox\n\n**Producer** = makes own food (plants)\n**Consumer** = eats other things\n**Decomposer** = breaks down dead matter', 22, true, '[{"question":"What do producers do?","options":["Eat plants","Eat animals","Make own food","Decompose"],"correct":2}]'),
('States of Matter Changes', 'Melting, freezing, more', 'science', 5, 20, '# State Changes\n\n**Melting** = solid → liquid\n**Freezing** = liquid → solid\n**Evaporation** = liquid → gas\n**Condensation** = gas → liquid\n**Sublimation** = solid → gas', 20, true, '[{"question":"Liquid to gas is...","options":["Melting","Freezing","Evaporation","Condensation"],"correct":2}]'),
('The Water Cycle', 'How water moves on Earth', 'science', 5, 22, '# Water Cycle\n\n**Evaporation** = water rises as vapor\n**Condensation** = clouds form\n**Precipitation** = rain, snow falls\n**Collection** = water gathers in lakes, oceans\n\nThe cycle repeats forever!', 22, true, '[{"question":"Clouds forming is...","options":["Evaporation","Condensation","Precipitation","Collection"],"correct":1}]'),
('Electricity Basics', 'Circuits and current', 'science', 5, 22, '# Electricity\n\n**Current** = flow of electrons\n**Circuit** = complete path for electricity\n**Conductor** = lets electricity flow (metal)\n**Insulator** = blocks electricity (rubber, plastic)\n\nCircuits need: power source, wire, load', 22, true, '[{"question":"What blocks electricity?","options":["Conductor","Metal","Insulator","Wire"],"correct":2}]'),
('Weathering and Erosion', 'Earth''s surface changes', 'science', 5, 20, '# Weathering & Erosion\n\n**Weathering** = breaking down rock\n- Physical (ice, water)\n- Chemical (acid rain)\n\n**Erosion** = moving broken rock\n- Wind, water, ice, gravity', 20, true, '[{"question":"Moving broken rock is...","options":["Weathering","Erosion","Deposition","Freezing"],"correct":1}]'),
('Inherited vs Learned Traits', 'Nature and nurture', 'science', 5, 20, '# Traits\n\n**Inherited** = from parents (genes)\n- Eye color, height potential, hair type\n\n**Learned** = from experience\n- Language, riding bike, reading\n\nBoth shape who we are!', 20, true, '[{"question":"Eye color is...","options":["Learned","Inherited","Neither","Both"],"correct":1}]'),
-- G5 Social (3 more)
('Colonial America', 'Early American settlements', 'social', 5, 25, '# Colonial America\n\n**13 Colonies** established by England\n\n**New England** = Massachusetts, Connecticut, Rhode Island, New Hampshire\n**Middle** = New York, Pennsylvania, New Jersey, Delaware\n**Southern** = Virginia, Maryland, Carolinas, Georgia', 25, true, '[{"question":"How many original colonies?","options":["10","13","15","50"],"correct":1}]'),
('Native American Cultures', 'First peoples of America', 'social', 5, 22, '# Native Americans\n\n**Regions shaped culture:**\n- Northwest: Fishing, totem poles\n- Plains: Buffalo hunters, tipis\n- Southwest: Pueblos, farming\n- Eastern Woodlands: Farming, longhouses', 22, true, '[{"question":"Plains tribes are known for hunting...","options":["Fish","Buffalo","Corn","Birds"],"correct":1}]'),
('Westward Expansion', 'Moving across America', 'social', 5, 22, '# Westward Expansion\n\n**Key Events:**\n- Louisiana Purchase (1803)\n- Lewis and Clark Expedition\n- Oregon Trail (1840s)\n- California Gold Rush (1849)\n- Transcontinental Railroad (1869)', 22, true, '[{"question":"Gold Rush was in...","options":["1776","1803","1849","1900"],"correct":2}]'),
-- G5 Lifeskills (2 more)
('Conflict Resolution', 'Solving disagreements peacefully', 'lifeskills', 5, 18, '# Conflict Resolution\n\n1. **Cool down** first\n2. **Listen** to understand\n3. **Use "I" statements** ("I feel...")\n4. **Find common ground**\n5. **Compromise** when possible\n\nRespect is key!', 18, true, '[{"question":"First step in conflict?","options":["Argue","Cool down","Walk away","Yell"],"correct":1}]'),
('Research Integrity', 'Being honest in school work', 'lifeskills', 5, 18, '# Academic Integrity\n\n**Do:**\n- Cite your sources\n- Use your own words\n- Ask if unsure\n\n**Don''t:**\n- Copy without credit\n- Let others copy you\n- Use unauthorized help', 18, true, '[{"question":"Using sources without credit is...","options":["OK","Plagiarism","Research","Smart"],"correct":1}]');