-- Add lessons to reach 50 per grade level
-- K needs 26 more, G1 needs 1, G2 needs 24, G4 needs 37, G5 needs 39, G6 needs 41, G7 needs 44, G8 needs 46

-- KINDERGARTEN (26 more lessons)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- K Reading (10 more)
('Vowel Sounds', 'A E I O U - the special letters!', 'reading', 0, 10, '# Vowels Are Special!\n\nVowels: A, E, I, O, U\n\nEvery word needs a vowel!\n\n**A** says "ah" in apple 🍎\n**E** says "eh" in elephant 🐘\n**I** says "ih" in igloo 🏠\n**O** says "oh" in octopus 🐙\n**U** says "uh" in umbrella ☂️', 10, true, '[{"question":"How many vowels are there?","options":["3","5","7"],"correct":1}]'),
('Word Families: -AT', 'Cat, hat, bat - words that rhyme!', 'reading', 0, 10, '# The -AT Family\n\nThese words end in -AT:\n- **C**at 🐱\n- **H**at 🎩\n- **B**at 🦇\n- **R**at 🐀\n- **M**at\n\nThey all rhyme!', 10, true, '[{"question":"Which word is in the -AT family?","options":["Dog","Cat","Pig"],"correct":1}]'),
('Word Families: -IG', 'Pig, big, dig - let''s rhyme!', 'reading', 0, 10, '# The -IG Family\n\n- **P**ig 🐷\n- **B**ig\n- **D**ig\n- **W**ig\n- **F**ig\n\nThey all end with the -ig sound!', 10, true, '[{"question":"Which rhymes with pig?","options":["Dog","Big","Cat"],"correct":1}]'),
('Story: The Lost Puppy', 'A heartwarming tale about kindness', 'reading', 0, 12, '# The Lost Puppy 🐕\n\nA little puppy was lost.\nHe was scared and lonely.\n\nA kind girl found him.\n"Don''t worry, I''ll help you!"\n\nShe took him home.\nThey found his family!\n\nThe puppy was happy.\nKindness helps everyone!', 15, true, '[{"question":"Who helped the puppy?","options":["A boy","A girl","A cat"],"correct":1}]'),
('Nursery Rhymes', 'Classic rhymes for fun!', 'reading', 0, 10, '# Nursery Rhymes 🎵\n\n**Twinkle Twinkle Little Star**\nTwinkle, twinkle, little star,\nHow I wonder what you are!\nUp above the world so high,\nLike a diamond in the sky!', 10, true, '[{"question":"What shines like a diamond?","options":["The sun","A star","The moon"],"correct":1}]'),
('Beginning Blends', 'Two letters make one sound!', 'reading', 0, 10, '# Letter Blends\n\n**BL** = Blue, Black\n**CL** = Clap, Cloud\n**FL** = Flower, Fly\n**GL** = Glad, Glue\n\nTwo letters work together!', 10, true, '[{"question":"What blend starts CLAP?","options":["BL","CL","FL"],"correct":1}]'),
('Story Sequencing', 'First, next, then, last!', 'reading', 0, 10, '# Story Order\n\n**First** - Wake up ☀️\n**Next** - Eat breakfast 🥣\n**Then** - Brush teeth 🦷\n**Last** - Go to school 🏫\n\nStories have order!', 10, true, '[{"question":"What comes FIRST?","options":["Eat breakfast","Wake up","Go to school"],"correct":1}]'),
('CVC Words', 'Consonant-Vowel-Consonant!', 'reading', 0, 10, '# CVC Words\n\nC-V-C = Consonant-Vowel-Consonant\n\n**C-A-T** = Cat 🐱\n**D-O-G** = Dog 🐕\n**S-U-N** = Sun ☀️\n**B-E-D** = Bed 🛏️', 10, true, '[{"question":"CAT has how many sounds?","options":["2","3","4"],"correct":1}]'),
('Reading Signs', 'Signs we see every day!', 'reading', 0, 8, '# Reading Signs 🪧\n\n**STOP** = Red octagon\n**EXIT** = Green arrow\n**OPEN** = Come in!\n**CLOSED** = Come back later\n\nSigns help us!', 10, true, '[{"question":"What color is a STOP sign?","options":["Green","Yellow","Red"],"correct":2}]'),
('Print Awareness', 'Words go left to right!', 'reading', 0, 8, '# How We Read\n\n📖 We read LEFT to RIGHT →\n📖 We read TOP to BOTTOM ↓\n📖 Words have spaces between them\n📖 Sentences end with a period.', 10, true, '[{"question":"Which way do we read?","options":["Right to left","Left to right","Bottom to top"],"correct":1}]'),
-- K Math (8 more)
('Numbers 1-5', 'Count with your fingers!', 'math', 0, 8, '# Counting 1-5 ✋\n\n1️⃣ One finger\n2️⃣ Two fingers\n3️⃣ Three fingers\n4️⃣ Four fingers\n5️⃣ Five fingers - one whole hand!', 10, true, '[{"question":"How many fingers on one hand?","options":["4","5","6"],"correct":1}]'),
('Comparing Sizes', 'Big and small, tall and short!', 'math', 0, 8, '# Size Words\n\n🐘 **BIG** - An elephant\n🐭 **SMALL** - A mouse\n🦒 **TALL** - A giraffe\n🐢 **SHORT** - A turtle', 10, true, '[{"question":"Which is BIGGER?","options":["Mouse","Elephant","Both same"],"correct":1}]'),
('Sorting Objects', 'Group things that are alike!', 'math', 0, 10, '# Sorting Fun!\n\nSort by COLOR:\n🔴🔴🔴 Red things together\n🔵🔵🔵 Blue things together\n\nSort by SIZE:\nBig things | Small things\n\nSort by SHAPE:\n⭕⭕ Circles | ⬛⬛ Squares', 10, true, '[{"question":"How can we sort?","options":["By color","By size","Both!"],"correct":2}]'),
('Position Words', 'Above, below, beside, between!', 'math', 0, 10, '# Where Is It?\n\n⬆️ **ABOVE** - The bird is above the tree\n⬇️ **BELOW** - The worm is below the ground\n↔️ **BESIDE** - The cat is beside the dog\n🔲 **BETWEEN** - I am between my friends', 10, true, '[{"question":"The sky is ___ us","options":["Below","Beside","Above"],"correct":2}]'),
('Zero the Hero', 'Zero means nothing - but it''s important!', 'math', 0, 8, '# Meet Zero! 0️⃣\n\nZero means nothing.\nAn empty cookie jar = 0 cookies\nNo birds on a branch = 0 birds\n\nBut zero is special!\n10 = 1 ten and 0 ones', 10, true, '[{"question":"Zero means...","options":["Nothing","One","Many"],"correct":0}]'),
('Subtracting to 5', 'Take away means subtract!', 'math', 0, 10, '# Taking Away ➖\n\n🍎🍎🍎 Take away 🍎 = 🍎🍎\n3 - 1 = 2\n\n⭐⭐⭐⭐ Take away ⭐⭐ = ⭐⭐\n4 - 2 = 2', 10, true, '[{"question":"5 - 2 = ?","options":["2","3","4"],"correct":1}]'),
('Making 10', 'Number pairs that make 10!', 'math', 0, 10, '# Friends of 10\n\n1 + 9 = 10\n2 + 8 = 10\n3 + 7 = 10\n4 + 6 = 10\n5 + 5 = 10\n\nThese pairs are "friends of 10"!', 10, true, '[{"question":"5 + ? = 10","options":["4","5","6"],"correct":1}]'),
('3D Shapes', 'Shapes you can hold!', 'math', 0, 10, '# 3D Shapes\n\n🔵 **Sphere** - Like a ball\n📦 **Cube** - Like a box\n🥫 **Cylinder** - Like a can\n🔺 **Cone** - Like an ice cream cone', 10, true, '[{"question":"A ball is a...","options":["Cube","Sphere","Cone"],"correct":1}]'),
-- K Science (4 more)
('Day and Night', 'When the sun sleeps, stars come out!', 'science', 0, 10, '# Day and Night 🌞🌙\n\n**DAY** ☀️\n- Sun is up\n- We play and learn\n- Animals wake up\n\n**NIGHT** 🌙\n- Moon and stars\n- We sleep\n- Owls wake up', 10, true, '[{"question":"When do we sleep?","options":["Day","Night","Noon"],"correct":1}]'),
('Living vs Non-Living', 'Is it alive?', 'science', 0, 10, '# Is It Alive?\n\n**LIVING** 🌱\n- Grows\n- Needs food and water\n- Can move\n(Plants, animals, people)\n\n**NON-LIVING** 🪨\n- Doesn''t grow\n- Doesn''t eat\n(Rocks, toys, books)', 10, true, '[{"question":"A tree is...","options":["Living","Non-living","Neither"],"correct":0}]'),
('Seasons Change', 'Spring, Summer, Fall, Winter!', 'science', 0, 10, '# Four Seasons 🍂\n\n🌸 **Spring** - Flowers bloom\n☀️ **Summer** - Hot and sunny\n🍂 **Fall** - Leaves change color\n❄️ **Winter** - Cold and snowy', 10, true, '[{"question":"When do leaves fall?","options":["Spring","Summer","Fall"],"correct":2}]'),
('Healthy Habits', 'Keep your body healthy!', 'science', 0, 8, '# Stay Healthy! 💪\n\n🥗 Eat fruits and veggies\n💧 Drink water\n🏃 Exercise and play\n😴 Get enough sleep\n🧼 Wash your hands', 10, true, '[{"question":"What should we drink?","options":["Soda","Water","Candy"],"correct":1}]'),
-- K Social/Life Skills (4 more)
('Following Rules', 'Rules keep us safe and happy!', 'lifeskills', 0, 8, '# Why Rules Matter 📋\n\nRules at school:\n- Walk, don''t run\n- Raise your hand\n- Listen to the teacher\n\nRules at home:\n- Be kind\n- Clean up toys\n- Say please and thank you', 10, true, '[{"question":"Rules help us be...","options":["Sad","Safe","Lost"],"correct":1}]'),
('Making Friends', 'How to be a friend', 'lifeskills', 0, 10, '# How to Make Friends 🤝\n\n1. Say "Hi!" and smile 😊\n2. Ask their name\n3. Share toys or snacks\n4. Take turns playing\n5. Be kind and helpful', 10, true, '[{"question":"Friends should...","options":["Share","Fight","Ignore"],"correct":0}]'),
('Safety First', 'Staying safe every day', 'lifeskills', 0, 10, '# Safety Rules 🦺\n\n🚗 Look both ways before crossing\n🔥 Don''t touch hot things\n💊 Only take medicine from parents\n📱 Tell parents before going anywhere\n👀 Stay where parents can see you', 10, true, '[{"question":"Before crossing, we...","options":["Run fast","Look both ways","Close eyes"],"correct":1}]'),
('Saying Sorry', 'Apologies make things better', 'lifeskills', 0, 8, '# How to Apologize\n\n1. Look at the person 👀\n2. Say "I''m sorry" sincerely\n3. Tell them what you did wrong\n4. Ask how to fix it\n5. Try not to do it again\n\n"I''m sorry" is a superpower!', 10, true, '[{"question":"When we hurt someone we should...","options":["Run away","Say sorry","Laugh"],"correct":1}]');

-- GRADE 1 (1 more lesson)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
('Silent E Magic', 'How E makes vowels say their name!', 'reading', 1, 12, '# Silent E Magic ✨\n\nWhen E comes at the end, the vowel says its NAME!\n\n**cap** → **cape** (A says "ay")\n**hop** → **hope** (O says "oh")\n**cut** → **cute** (U says "you")\n**kit** → **kite** (I says "eye")\n\nSilent E is magic!', 12, true, '[{"question":"What does silent E do?","options":["Makes noise","Makes vowels say their name","Nothing"],"correct":1}]');

-- GRADE 2 (24 more lessons)
INSERT INTO lessons (title, description, subject, grade_level, estimated_minutes, content_markdown, points_value, is_active, quiz_questions) VALUES
-- G2 Reading (8)
('Prefixes: UN and RE', 'Word beginnings that change meaning!', 'reading', 2, 12, '# Prefixes Change Words!\n\n**UN-** means NOT:\n- happy → **un**happy (not happy)\n- kind → **un**kind (not kind)\n\n**RE-** means AGAIN:\n- read → **re**read (read again)\n- do → **re**do (do again)', 15, true, '[{"question":"Unhappy means...","options":["Very happy","Not happy","Always happy"],"correct":1}]'),
('Suffixes: -LY and -FUL', 'Word endings that add meaning!', 'reading', 2, 12, '# Suffixes Add Meaning!\n\n**-LY** tells HOW:\n- quick → quick**ly** (how you move)\n- slow → slow**ly**\n\n**-FUL** means FULL OF:\n- hope → hope**ful** (full of hope)\n- care → care**ful**', 15, true, '[{"question":"Carefully means...","options":["With care","Without care","Caring less"],"correct":0}]'),
('Main Idea', 'What is the story mainly about?', 'reading', 2, 15, '# Finding the Main Idea 💡\n\nThe main idea is what the story is MOSTLY about.\n\n**How to find it:**\n1. Read the whole text\n2. Ask: What is this mostly about?\n3. The title often gives clues\n\n**Example:** A story about a dog learning tricks → Main idea: A dog learns new tricks.', 15, true, '[{"question":"Main idea is...","options":["A small detail","What it is mostly about","The first sentence"],"correct":1}]'),
('Character Traits', 'Words that describe characters', 'reading', 2, 12, '# Describing Characters\n\nCharacter traits tell us WHO someone is:\n\n😊 **Kind** - Helps others\n💪 **Brave** - Faces fears\n🧠 **Clever** - Solves problems\n😤 **Stubborn** - Won''t change mind\n😁 **Funny** - Makes people laugh', 15, true, '[{"question":"A brave character...","options":["Runs from danger","Faces their fears","Is always sad"],"correct":1}]'),
('Fiction vs Nonfiction', 'Made-up or real?', 'reading', 2, 12, '# Two Types of Books\n\n📖 **FICTION** - Made-up stories\n- Fairy tales\n- Fantasy\n- Stories with talking animals\n\n📚 **NONFICTION** - Real information\n- Science books\n- Biographies\n- How-to books', 15, true, '[{"question":"A book about a talking dragon is...","options":["Fiction","Nonfiction","Neither"],"correct":0}]'),
('Context Clues', 'Figure out word meanings!', 'reading', 2, 15, '# Using Context Clues 🔍\n\nWhen you don''t know a word, look for CLUES nearby!\n\n**Example:** The enormous elephant was huge!\n"Enormous" means = HUGE (the clue!)\n\n**Tips:**\n- Read the sentence around it\n- Look for synonyms\n- Use picture clues', 15, true, '[{"question":"Context clues help us...","options":["Skip words","Understand word meanings","Forget words"],"correct":1}]'),
('Asking Questions', 'Good readers ask questions!', 'reading', 2, 12, '# Question Words ❓\n\n**WHO** - Which person?\n**WHAT** - Which thing?\n**WHEN** - What time?\n**WHERE** - Which place?\n**WHY** - What reason?\n**HOW** - In what way?\n\nAsking questions helps you understand!', 15, true, '[{"question":"WHERE asks about...","options":["Time","Place","Reason"],"correct":1}]'),
('Poetry Reading', 'Poems are fun to read!', 'reading', 2, 15, '# Reading Poetry 🎭\n\n**Poems have:**\n- Rhymes (words that sound alike)\n- Rhythm (a beat)\n- Feelings and images\n\n**Example:**\n*The cat sat on the mat,*\n*Wearing a funny hat!*\n\n"Cat," "mat," and "hat" rhyme!', 15, true, '[{"question":"Poems often have...","options":["Rhymes","Only facts","No feelings"],"correct":0}]'),
-- G2 Math (8)
('Even and Odd', 'Numbers have partners - or not!', 'math', 2, 12, '# Even & Odd Numbers\n\n**EVEN** numbers pair up:\n2, 4, 6, 8, 10... (ends in 0,2,4,6,8)\n\n**ODD** numbers have one left over:\n1, 3, 5, 7, 9... (ends in 1,3,5,7,9)\n\n💡 Even numbers can be split in half evenly!', 15, true, '[{"question":"Is 7 even or odd?","options":["Even","Odd","Neither"],"correct":1}]'),
('Skip Counting by 5s', 'Count faster with 5s!', 'math', 2, 10, '# Counting by 5s\n\n5, 10, 15, 20, 25, 30, 35, 40, 45, 50!\n\n**Tip:** Count nickels this way!\n🪙🪙🪙🪙 = 5, 10, 15, 20 cents\n\n**Pattern:** Always ends in 0 or 5!', 12, true, '[{"question":"What comes after 25 when counting by 5s?","options":["26","30","35"],"correct":1}]'),
('Addition with Regrouping', 'When ones add up to 10 or more!', 'math', 2, 15, '# Regrouping (Carrying)\n\n**Problem:** 28 + 15 = ?\n\n**Step 1:** Add ones: 8 + 5 = 13\nThat''s 1 ten and 3 ones!\n\n**Step 2:** Carry the 1 to tens\n2 + 1 + 1 = 4 tens\n\n**Answer:** 43', 15, true, '[{"question":"28 + 15 = ?","options":["33","43","53"],"correct":1}]'),
('Subtraction with Regrouping', 'Borrowing from the tens!', 'math', 2, 15, '# Regrouping in Subtraction\n\n**Problem:** 42 - 17 = ?\n\n**Step 1:** Can''t take 7 from 2!\nBorrow 1 ten → now 12 ones\n\n**Step 2:** 12 - 7 = 5\n**Step 3:** 3 - 1 = 2 (one ten was borrowed)\n\n**Answer:** 25', 15, true, '[{"question":"42 - 17 = ?","options":["25","35","15"],"correct":0}]'),
('Arrays', 'Rows and columns of objects!', 'math', 2, 12, '# Understanding Arrays\n\n🍎🍎🍎\n🍎🍎🍎\n\nThis array has:\n- 2 **rows** (across)\n- 3 **columns** (up and down)\n- 2 × 3 = 6 apples total!\n\nArrays show multiplication!', 12, true, '[{"question":"An array with 3 rows of 4 has how many total?","options":["7","12","34"],"correct":1}]'),
('Measuring Length', 'How long is it?', 'math', 2, 12, '# Measuring with a Ruler 📏\n\n**Inches** - Shorter things (pencils)\n**Feet** - Medium things (desks)\n**Yards** - Longer things (rooms)\n\n12 inches = 1 foot\n3 feet = 1 yard\n\nLine up at ZERO, read the number at the end!', 15, true, '[{"question":"How many inches in 1 foot?","options":["10","12","15"],"correct":1}]'),
('Word Problems', 'Math stories to solve!', 'math', 2, 15, '# Solving Word Problems\n\n**CUBES Strategy:**\n- **C**ircle the numbers\n- **U**nderline the question\n- **B**ox key words (total, left, more)\n- **E**valuate the operation (+, -, ×)\n- **S**olve and check!', 15, true, '[{"question":"\"Total\" usually means...","options":["Subtract","Add","Divide"],"correct":1}]'),
('Graphing Data', 'Show information with pictures!', 'math', 2, 12, '# Making Graphs 📊\n\n**Bar Graph** - Bars show amounts\n**Pictograph** - Pictures show amounts\n\n**Reading a Graph:**\n1. Read the title\n2. Look at labels\n3. Count or compare bars/pictures', 15, true, '[{"question":"A pictograph uses...","options":["Bars","Pictures","Only numbers"],"correct":1}]'),
-- G2 Science (4)
('Habitats', 'Where do animals live?', 'science', 2, 15, '# Animal Habitats 🏠\n\n**Desert** 🏜️ - Hot, dry (camels, lizards)\n**Ocean** 🌊 - Saltwater (fish, whales)\n**Forest** 🌲 - Trees (deer, squirrels)\n**Arctic** 🧊 - Cold, icy (polar bears, penguins)\n\nAnimals fit their habitat!', 15, true, '[{"question":"Polar bears live in the...","options":["Desert","Ocean","Arctic"],"correct":2}]'),
('Food Chains', 'Who eats who?', 'science', 2, 15, '# The Food Chain 🔗\n\n☀️ Sun gives energy to...\n🌱 Plants (producers) eaten by...\n🐰 Herbivores (plant-eaters) eaten by...\n🦁 Carnivores (meat-eaters)\n\nEnergy flows through the chain!', 15, true, '[{"question":"Plants are called...","options":["Consumers","Producers","Decomposers"],"correct":1}]'),
('Properties of Matter', 'What is it like?', 'science', 2, 12, '# Describing Matter\n\n**Properties** tell us about objects:\n\n- **Size** - big or small?\n- **Color** - red, blue, green?\n- **Shape** - round, square?\n- **Texture** - smooth or rough?\n- **Weight** - heavy or light?', 15, true, '[{"question":"Texture describes...","options":["Color","How it feels","Size"],"correct":1}]'),
('Push and Pull', 'Forces make things move!', 'science', 2, 12, '# Push and Pull Forces 💪\n\n**PUSH** = Move away from you\n- Pushing a door\n- Throwing a ball\n\n**PULL** = Move toward you\n- Opening a drawer\n- Pulling a wagon\n\nForces make things move!', 15, true, '[{"question":"Opening a drawer is a...","options":["Push","Pull","Neither"],"correct":1}]'),
-- G2 Social/Life (4)
('Being a Good Citizen', 'Helping our community!', 'social', 2, 12, '# Good Citizens\n\n**At School:**\n- Follow rules\n- Help classmates\n- Take care of property\n\n**In Community:**\n- Recycle\n- Be kind to neighbors\n- Vote when grown up', 15, true, '[{"question":"Good citizens...","options":["Follow rules","Break rules","Ignore others"],"correct":0}]'),
('Needs vs Wants', 'What we must have vs what we wish for', 'social', 2, 12, '# Needs and Wants\n\n**NEEDS** (must have):\n🏠 Shelter\n🍎 Food\n💧 Water\n👕 Clothing\n\n**WANTS** (nice to have):\n🎮 Video games\n🍦 Ice cream\n🎁 New toys', 15, true, '[{"question":"Food is a...","options":["Want","Need","Neither"],"correct":1}]'),
('Handling Disappointment', 'It''s okay to be sad sometimes', 'lifeskills', 2, 12, '# When Things Don''t Go Our Way\n\n**It''s okay to feel sad!**\n\n**What to do:**\n1. Take deep breaths\n2. Talk about your feelings\n3. Think of something good\n4. Try again later\n\nDisappointment is part of life!', 15, true, '[{"question":"When disappointed, we should...","options":["Give up forever","Take deep breaths","Be mean to others"],"correct":1}]'),
('Cooperation', 'Working together is better!', 'lifeskills', 2, 12, '# Teamwork 🤝\n\n**Cooperation** means working together!\n\n**How to cooperate:**\n- Listen to others'' ideas\n- Take turns\n- Help each other\n- Compromise\n- Celebrate together!', 15, true, '[{"question":"Cooperation means...","options":["Working alone","Working together","Not helping"],"correct":1}]');